# https://hub.docker.com/_/ubuntu
FROM ubuntu:16.04 


ENV PAKETTO_VERSION 1.10

RUN set -xe && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && apt-get -qqy upgrade

# install zmap build dependencies
RUN set -xe && \
    http://www.doxpara.com/paketto/paketto-${PAKETTO_VERSION}.tar.gz
