# https://hub.docker.com/_/ubuntu
FROM ubuntu:16.04 


ENV PAKETTO_VERSION 1.10

RUN set -xe && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && apt-get -qqy upgrade

RUN set -xe && \
    apt-get install masscan -y
