# https://hub.docker.com/_/ubuntu
FROM ubuntu:16.04 

RUN set -xe && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get -qq update && apt-get -qqy upgrade

RUN set -xe && \
    #https://nmap.org/zenmap/
    apt-get install zenmap -y

ENTRYPOINT ["zmap"]
CMD ["-h"]
